### PR TITLE
Correct font associations in Fontmap.MiKTeX

### LINKED ISSUE #431: Incorrect font associations in Fontmap.MiKTeX
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi, I have done a thorough check of all font associations in `Fontmap.MiKTeX` (last modified on 2010-09-23, 😮) using the following batch:
```
@REM /Courier-Bold (type1/adobe/courier/pcrb8a.pfb) ;
@FOR /F "tokens=1,2 delims=()" %%a IN (../ghostscript/base/Fontmap.MiKTeX) DO @(
  @IF NOT EXIST %%b (
    ECHO %%a
    ECHO %%b
    DIR /S/B %%~nxb
    ECHO.
  )
)
```

After installing all packages that contain `*.pfb` files (there are 3167 exclusively `*.pfb` associations in `Fontmap.MiKTeX`), and running the above script from `C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\fonts`, I got the following:
[out.txt](https://github.com/MiKTeX/miktex/files/3934397/out.txt)

As you can see, some resources are not available at all and some are available at different locations (not necessarily unique, we should be careful).

I will try to address them in groups (probably in several steps) and suggest needed changes. It would be good to have `Fontmap.MiKTeX` versioned under git - do you mind if I add it somewhere within my fork (and where)?

Kind regards, Ivan

### PR DESCRIPTION
**Pull request by ivankokan**
Resolves #431.

### CODE REVIEW

**Comment by ivankokan** [comment]
All incorrect associations with replacement candidates are now resolved:
[out1.txt](https://github.com/MiKTeX/miktex/files/3956205/out1.txt)

It remains to:

- Comment all missing/invalid/obsolete associations.
- Add missing associations for all installed `*.pfb` resources.
- Verify uniqueness of all associations.
- Sort all associations by folder (future-proof).

**Comment by ivankokan** [comment]
Aftermath:

- VBScript script `genFontmap.vbs` can be used for regular maintenance. All future diffs using that script will be sound and naturally located within `Fontmap.MiKTeX` (due to consistent sorting).
- Font resource `type1/public/ebgaramond/EBGaramondInitialsLCDFJ.pfb` does not contain FontName; it is actually a zero-byte file.
- There are still ~130 non-unique font associations due to various reasons, e.g. `type1/adobe/courier/pcrbi8a.pfb` and `type1/adobe/courier/pcrbo8a.pfb` (for `Courier-BoldItalic`) are exactly the same, while `type1/public/sansmathfonts/cmsmfIPiXixi10.pfb` and `type1/public/sansmathfonts/cmsmfIPiXixicsc10.pfb` (for `ComputerModern-ItalicRegularExtended10pt`) are not.

Any feedback is highly appreciated.

Kind regards, Ivan

**Comment by edocevoli** [comment]
Thank you. I will merge your commit as soon as possible.

**Comment by ivankokan** [comment]
I confirm that updates are now available.

**Pull request merged**
